#!/usr/bin/env bash

# Name: Atharva Adhikari
# ID: 25049366
# Version Number: 6
# Date of completion: 22 May 2026

if [[ $# -ne 1 ]]; then
    echo "ERROR: No input CSV file provided"
    exit 1
fi

INPUT_FILE="$1"

if [[ ! -f "$INPUT_FILE" ]]; then
    echo "ERROR: Input file not found in the current directory"
    exit 1
fi

if [[ "$INPUT_FILE" != *.csv ]]; then
    echo "ERROR: Input file expected in a CSV format"
    exit 1
fi

if [[ ! -s "$INPUT_FILE" ]]; then
    echo "ERROR: Empty file provided"
    exit 1
fi

awk -F',' '

BEGIN {
    OFS = ","

    maxFreq = 0
    maxDislikes = -1
    maxEngagement = -1
    minSentiment = 999999
    totalViews = 0
    count = 0
    maxEngagementSet = 0
    minSentimentSet = 0
}

NR > 1 {

    if ($3 <= 0 || $4 <= 0 || $5 <= 0)
        next

    video_id = $1
    publish_date = $2
    views = $3
    likes = $4
    dislikes = $5

    freq[video_id]++

    totalViews += views
    count++

    if (dislikes > maxDislikes) {

        maxDislikes = dislikes

        delete maxDislikeVideos

        maxDislikeVideos[video_id] = 1
    }

    else if (dislikes == maxDislikes) {

        maxDislikeVideos[video_id] = 1
    }

    engagement = (likes + dislikes) / views

    if (!maxEngagementSet || engagement > maxEngagement) {

        maxEngagement = engagement
        maxEngagementSet = 1

        delete engagementVideos

        engagementVideos[video_id "," publish_date] = 1
    }

    else if (engagement == maxEngagement) {

        engagementVideos[video_id "," publish_date] = 1
    }

    sentiment = (likes - dislikes) / views

    if (!minSentimentSet || sentiment < minSentiment) {

        minSentiment = sentiment
        minSentimentSet = 1

        delete sentimentVideos

        sentimentVideos[video_id "," publish_date] = 1
    }

    else if (sentiment == minSentiment) {

        sentimentVideos[video_id "," publish_date] = 1
    }
}

END {

    for (id in freq) {

        if (freq[id] > maxFreq)
            maxFreq = freq[id]
    }

    printf "Most frequent video, ID: "

    sep = ""

    for (id in freq) {

        if (freq[id] == maxFreq) {

            printf "%s%s", sep, id
            sep = ", "
        }
    }

    printf "\n"

    meanViews = totalViews / count

    printf "Mean number of views: %.2f\n", meanViews

    printf "Max dislikes video, ID: "

    sep = ""

    for (id in maxDislikeVideos) {

        printf "%s%s", sep, id
        sep = ", "
    }

    printf "\n"

    printf "Highest engagement rate video, ID: "

    sep = ""

    for (entry in engagementVideos) {

        split(entry, arr, ",")

        printf "%s%s", sep, arr[1]
        sep = ", "
    }

    printf ", dated: "

    sep = ""

    for (entry in engagementVideos) {

        split(entry, arr, ",")

        printf "%s%s", sep, arr[2]
        sep = ", "
    }

    printf "\n"

    printf "Least sentiment rate video, ID: "

    sep = ""

    for (entry in sentimentVideos) {

        split(entry, arr, ",")

        printf "%s%s", sep, arr[1]
        sep = ", "
    }

    printf ", dated: "

    sep = ""

    for (entry in sentimentVideos) {

        split(entry, arr, ",")

        printf "%s%s", sep, arr[2]
        sep = ", "
    }

    printf "\n"
}
' "$INPUT_FILE"