#!/usr/bin/env bash
# Name: Atharva Adhikari
# ID: 25049366
# Version Number: 3
# Date of completion: 22 May 2026
# How to run this script: ./clean trending_videos_unclean.csv
# Summary: The given script performs data cleaning on a CSV file containing YouTube trending video data. It checks for various error conditions such as missing input file, incorrect file format, and empty file. The script processes the CSV file using awk, removing rows with incorrect number of columns, missing values, and zero likes/dislikes. It also formats the publish date and converts TRUE/FALSE values to True/False. Finally, it removes duplicate rows and saves the cleaned data to a new CSV file named "trending_videos_clean.csv".

# ERROR_CHECKS

# 1) No input file specified
if [ $# -eq 0 ]; then
    echo "ERROR: No input CSV file provided"
    exit 1
fi

INPUT_FILE="$1"

# 2) Input file not found
if [ ! -f "$INPUT_FILE" ]; then
    echo "ERROR: Input file not found in the current directory"
    exit 1
fi

# 3) Input file is not CSV
if [[ "$INPUT_FILE" != *.csv ]]; then
    echo "ERROR: Input file expected in a CSV format"
    exit 1
fi

# 4) Input file is empty
if [ ! -s "$INPUT_FILE" ]; then
    echo "ERROR: Empty file provided"
    exit 1
fi


OUTPUT_FILE="trending_videos_clean.csv"

awk -F',' '
BEGIN {
    OFS=","
}

# Process header
NR == 1 {

    # Ensure header has 7 columns
    if (NF != 7) {
        print "ERROR: Expected 7 columns in the input"
        exit 1
    }

    # Remove ratings_disabled column
    print $1, $2, $3, $4, $5, $6
    next
}

{

    # Delete rows with incorrect number of columns
    if (NF != 7)
        next

    # Delete rows with missing values
    for ( i = 0; i <=NF; i++ )
        if ($i == "")
            next

    # Delete rows with zero likes/dislikes
    if ($4 == 0 || $5 == 0)
        next

    # Remove time from publish_date
    split($2, dateParts, "T")
    cleanDate = dateParts[1]

    # Convert TRUE/FALSE to True/False
    if ($6 == "TRUE")
        comments = "True"
    else if ($6 == "FALSE")
        comments = "False"
    else
        comments = $6

    # Create cleaned row
    row = $1 OFS cleanDate OFS $3 OFS $4 OFS $5 OFS comments

    # Remove duplicate rows
    if (!seen[row]++) {
        print row
    }
}
' "$INPUT_FILE" > "$OUTPUT_FILE"

echo "Data cleaning complete."
echo "Cleaned file created: $OUTPUT_FILE"
